config/routes.rb
Rails.application.routes.draw do
  resources :audio_notes

  get 'homes/index'
  get '/settings' => 'settings#index'

  root "homes#index"

  resources :songs

  resources :bands do
    resources :band_invites do
      collection do
        get 'activate'
      end
    end
    resources :songs do
      collection do
        post 'sort'
      end
      resources :audio_clips
    end
  end

  get 'dashboard/index'

  resources :users
  get 'sign_up' => 'users#new'

  resource :session
  delete 'sign_out' => 'sessions#destroy'
  get 'sign_in' => 'sessions#new'

  post 'set_active_band' => 'users#set_active_band'

end

app/models/audio_clip.rb
class AudioClip < ActiveRecord::Base
  belongs_to :song
  has_many :audio_notes
  mount_uploader :audio_file, AudioFileUploader
end

app/models/audio_note.rb
class AudioNote < ActiveRecord::Base
  belongs_to :audio_clip

  def format_time
    string = self.time.to_s
    seconds, second = string.split(".")
    minutes = 0
    seconds = seconds.to_i
    while seconds >= 60
      seconds -= 60
      minutes += 1
    end
    minutes.to_s.rjust(1,'0') + ":" + seconds.to_s.rjust(2,'0')
  end
end

app/models/band.rb
class Band < ActiveRecord::Base
  has_many :songs
  has_many :bands_users
  has_many :users, through: :bands_users
end

app/models/band_invite.rb
class BandInvite < ActiveRecord::Base
  before_create :generate_token

  belongs_to :band
  belongs_to :user

  def generate_token
    self.token = Digest::SHA1.hexdigest([self.band_id, Time.now, rand].join)
  end
end

app/models/bands_user.rb
class BandsUser < ActiveRecord::Base
  validates :user_id, uniqueness: { scope: :band_id }
  belongs_to :band
  belongs_to :user
end

app/models/song.rb
class Song < ActiveRecord::Base
  include ActionView::Helpers::SanitizeHelper
  after_validation :sanitize_lyrics
  default_scope { order('position') }
  has_many :audio_clips
  belongs_to :band

  validates :name, :band, presence: true
  validates :name, length: { maximum: 30 }

  def sanitize_lyrics
    if lyrics
      unless strip_tags(lyrics.strip.chomp) =~ /\w/
        self.lyrics = nil
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :first_name, :last_name, presence: true

  before_create :generate_token
  after_validation :set_active_band

  has_secure_password

  belongs_to :active_band, foreign_key: :band_id, class_name: 'Band'

  has_many :bands_users
  has_many :bands, through: :bands_users

  validates :password,
    length: { in: 8..32},
    allow_nil: true
  validates :email,
    uniqueness: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def generate_token
    begin
      self[:auth_token] = SecureRandom.urlsafe_base64
    end while User.exists?(:auth_token => self[:auth_token])
  end

  def set_active_band
    if !self.active_band && self.bands.count > 0
      self.active_band = self.bands.last
    end
  end

  def regenerate_auth_token
    self.auth_token = nil
    generate_token
    save!
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :update]
  before_action :require_login

  def new
    @band = Band.new
  end

  def create
    @band = current_user.bands.build(band_params)
    if current_user.save
      current_user.update(active_band: @band)
      redirect_to root_url, notice: 'Band created successfully!'
    else
      render :new, alert: 'Could not create band.'
    end
  end

  def show
    @song = Song.new
  end

  def update
    if @band.update(band_params)
      redirect_to @band
    else
      redirect_to :back
    end
  end

  private

  def set_band
    @band = Band.find(params[:id])
  end

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_login

  def index
    redirect_to _
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :require_login

  def index
    if current_user.bands.count == 0
      redirect_to new_band_path
    else
      redirect_to current_user.active_band
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      if params[:remember_me]
        permanent_sign_in(@user)
      else
        sign_in(@user)
      end
      flash[:success] = "Signed in!"
      redirect_to root_url
    else
      flash.now[:error] = "Incorrect username or password."
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_url, notice: 'Signed out successfully!'
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def new
    @band = Band.find(params[:band_id])
    @song = Song.new
  end

  def create
    @band = Band.find(params[:band_id])
    @song = @band.songs.build(song_params)
    if @song.save
      respond_to do |format|
        format.html { redirect_to @band }
        format.json { render json: { name: @song.name } }
      end
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def destroy
    if @song.destroy
      redirect_to :back
    end
  end

  def update
    if @song.update(song_params)
      respond_to do |format|
        format.html { redirect_to @song }
        format.json { render json: { success: true } }
      end
    else
      render :edit
    end
  end

  def lyrics
  end

  def sort
    params[:song].each_with_index do |id, index|
      song = Song.find(id)
      song.update(position: index + 1)
    end
    render nothing: true
    # respond_to do |format|
    #   format.json { render json: {success: true}}
    # end
  end

  private

  def set_song
    @song = Song.find(params[:id])
    @band = @song.band
  end

  def song_params
    params.require(:song).permit(:name, :band_id, :lyrics)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if params[:invite_token]
      @invite = BandInvite.find_by_token(params[:invite_token])
      @user.bands << @invite.band
    end
    if @user.save
      sign_in(@user)
      redirect_to root_url, notice: 'Account created!'
    else
      render :new, alert: 'Could not create account!'
    end
  end

  def set_active_band
    if band = Band.find(params[:band_id])
      current_user.update(active_band: band)
      redirect_to band
    else
      redirect_to :back
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-danger", notice: "alert-success" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type.to_sym)} fade in") do
        concat content_tag(:button, '', class: "glyphicon glyphicon-remove close")
        concat message
      end)
    end
    nil
  end

end

app/helpers/audio_clips_helper.rb
module AudioClipsHelper
end

app/helpers/audio_notes_helper.rb
module AudioNotesHelper
end

app/helpers/band_invites_helper.rb
module BandInvitesHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
  def lyric_format(string)
    string = string.split /\//
    string = string.map { |phrase| "<span class='phrase'>#{phrase}</span>" }.join
    simple_format(string)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bands/new.html.slim
.row
  .col-sm-4.col-sm-offset-4
    h1 New Band
    .well
      = form_for @band do |f|
        .form-group
          = f.label :name
          = f.text_field :name, class: 'form-control'
        = f.submit class: 'btn btn-primary'

app/views/bands/show.html.slim
h1
  = link_to @band.name, "#", class: 'band-name active'

/br

/h5
/  | Next Practice in
/  em  3 days...
/
/h5
/  | Next Show in
/  em  2 weeks...

br

.row
  .col-sm-6
    .songs-container.songs-color
      .title SONGS
      .song-links data-update-url=(sort_band_songs_url(@band))
        - @band.songs.each do |song|
          .song.song-link id=("song_#{song.id}")
            span.underline
              = link_to song.name, song, class: 'song-a'
            |  
            small
              = link_to song, method: :delete, data: { confirm: 'Are you sure you want to delete this song?'} do
                span.glyphicon.glyphicon-remove
      .song.add-song
        = link_to '#', class: 'add-song inactive', data: { target: 'song-form-1'} do
          small
            span.glyphicon.glyphicon-plus
        .song-form#song-form-1
          = form_for [@band,@song] do |f|
            = f.text_field :name, placeholder: 'New Song'


  .col-sm-6
    .songs-container
      .title MEMBERS
      - @band.users.each do |user|
        .song.song-link
          span.underline
            = link_to user.full_name, user, class: 'song-a'
      .song.add-song
        = link_to '#', class: 'add-song inactive', data: { target: 'member-form-1' } do
          small
            span.glyphicon.glyphicon-plus
        .song-form#member-form-1
          = form_tag band_band_invites_path(@band) do
            = hidden_field_tag 'band_invite[band_id]', @band.id
            = text_field_tag :email, "", placeholder: 'New Member Email'
  /.col-sm-6
  /  .panel.panel-default
  /    .panel-heading
  /      .panel-title
  /        | Members
  /    .songs.list-group
  /      - @band.users.each do |user|
  /        = link_to user.email, user, class: 'list-group-item'
  /
  /

app/views/songs/edit.html.slim
h1
  = link_to @band.name, @band, class: 'band-name'
  |   
  = link_to @song.name, [@band,@song], class: 'band-name'
  |   
  = link_to "Lyrics", '#', class: 'band-name active'

hr

.panel.panel-default
  .panel-heading
    .panel-title
      | Lyrics
  .panel-body.lyrics
    = form_for [@band, @song] do |f|
      = f.text_area :lyrics
      = f.submit

app/views/songs/new.html.slim
.row
  .col-sm-4.col-sm-offset-4
    h1 New Song
    .well
      = form_for [@band, @song] do |f|
        .form-group
          = f.label :name
          = f.text_field :name, class: 'form-control', autofocus: true
        = f.submit class: 'btn btn-primary'

app/views/songs/show.html.slim
h1
  = link_to @band.name, @band, class: 'band-name'
  |   
  .link-section.song-name-link data-update-url=(song_path(@song))
    = link_to @song.name, "#", class: 'band-name active'
    .control.edit-name EDIT

br

.row
  .col-sm-6
    .lyrics-container
      .title LYRICS
      /.control EDIT
      .lyrics contentEditable='false' data-update-url=(song_path(@song)) class=('placeholder' unless @song.lyrics)
        = @song.lyrics.try(:html_safe)
      .control EDIT
      /button id='edit-lyrics' Edit

  .col-sm-6
    .clips-container
      .title CLIPS
      - @song.audio_clips.each do |clip|
        .clip data-id=(clip.id)
          | Uploaded 
          = time_ago_in_words(clip.created_at)
          |  Ago
          = audio_tag clip.audio_file.url, preload: "auto"
          = link_to "Add Note", "#", class: 'add-clip-note'
          .notes
            - clip.audio_notes.each do |note|
              .audio-note
                .set-clip-time data-time=(note.time)
                  = note.format_time
                .note = note.note

    = link_to "Add Audio", new_band_song_audio_clip_path(@band, @song), class: 'btn btn-primary'

app/views/users/index.html.slim
h1 Index

app/views/users/new.html.slim
.row
  .col-sm-4.col-sm-offset-4
    h1 Sign Up
    br
    .well
      = form_for @user do |f|
        - if params[:invite_token]
          = hidden_field_tag :invite_token, params[:invite_token]
        .form-group
          = f.label :email
          = f.text_field :email, class: 'form-control', placeholder: 'Email Address', autofocus: true
        .row
          .form-group.col-sm-6
            = f.label :first_name
            = f.text_field :first_name, class: 'form-control', placeholder: 'First Name'
          .form-group.col-sm-6
            = f.label :last_name
            = f.text_field :last_name, class: 'form-control', placeholder: 'Last Name'
        .form-group
          = f.label :password
          = f.password_field :password, class: 'form-control', placeholder: 'Password'
        .form-group
          = f.label :password_confirmation
          = f.password_field :password_confirmation, class: 'form-control', placeholder: 'Password Confirmation'
        = f.submit "Sign Up", class: 'btn btn-primary'

      br
      = link_to "Sign In", sign_in_path

app/views/users/show.html.slim
h1
  = link_to @user.full_name, @user, class: 'band-name active'