config/routes.rb
Rails.application.routes.draw do
  resources :audio_notes

  get 'homes/index'
  get '/settings' => 'settings#index'

  root "homes#index"

  resources :songs

  resources :bands do
    resources :band_invites do
      collection do
        get 'activate'
      end
    end
    resources :songs do
      collection do
        post 'sort'
      end
      resources :audio_clips
    end
  end

  get 'dashboard/index'

  resources :users
  get 'sign_up' => 'users#new'

  resource :session
  delete 'sign_out' => 'sessions#destroy'
  get 'sign_in' => 'sessions#new'

  post 'set_active_band' => 'users#set_active_band'

end

app/models/audio_clip.rb
class AudioClip < ActiveRecord::Base
  belongs_to :song
  has_many :audio_notes
  mount_uploader :audio_file, AudioFileUploader
end

app/models/audio_note.rb
class AudioNote < ActiveRecord::Base
  belongs_to :audio_clip

  def format_time
    string = self.time.to_s
    seconds, second = string.split(".")
    minutes = 0
    seconds = seconds.to_i
    while seconds >= 60
      seconds -= 60
      minutes += 1
    end
    minutes.to_s.rjust(1,'0') + ":" + seconds.to_s.rjust(2,'0')
  end
end

app/models/band.rb
class Band < ActiveRecord::Base
  has_many :songs
  has_many :bands_users
  has_many :users, through: :bands_users
end

app/models/band_invite.rb
class BandInvite < ActiveRecord::Base
  before_create :generate_token

  belongs_to :band
  belongs_to :user

  def generate_token
    self.token = Digest::SHA1.hexdigest([self.band_id, Time.now, rand].join)
  end
end

app/models/bands_user.rb
class BandsUser < ActiveRecord::Base
  validates :user_id, uniqueness: { scope: :band_id }
  belongs_to :band
  belongs_to :user
end

app/models/song.rb
class Song < ActiveRecord::Base
  include ActionView::Helpers::SanitizeHelper
  after_validation :sanitize_lyrics
  default_scope { order('position') }
  has_many :audio_clips
  belongs_to :band

  validates :name, :band, presence: true
  validates :name, length: { maximum: 30 }

  def sanitize_lyrics
    if lyrics
      unless strip_tags(lyrics.strip.chomp) =~ /\w/
        self.lyrics = nil
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :first_name, :last_name, presence: true

  before_create :generate_token
  after_validation :set_active_band

  has_secure_password

  belongs_to :active_band, foreign_key: :band_id, class_name: 'Band'

  has_many :bands_users
  has_many :bands, through: :bands_users

  validates :password,
    length: { in: 8..32},
    allow_nil: true
  validates :email,
    uniqueness: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def generate_token
    begin
      self[:auth_token] = SecureRandom.urlsafe_base64
    end while User.exists?(:auth_token => self[:auth_token])
  end

  def set_active_band
    if !self.active_band && self.bands.count > 0
      self.active_band = self.bands.last
    end
  end

  def regenerate_auth_token
    self.auth_token = nil
    generate_token
    save!
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :update]
  before_action :require_login

  def new
    @band = Band.new
  end

  def create
    @band = current_user.bands.build(band_params)
    if current_user.save
      current_user.update(active_band: @band)
      redirect_to root_url, notice: 'Band created successfully!'
    else
      render :new, alert: 'Could not create band.'
    end
  end

  def show
    @song = Song.new
  end

  def update
    if @band.update(band_params)
      redirect_to @band
    else
      redirect_to :back
    end
  end

  private

  def set_band
    @band = Band.find(params[:id])
  end

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :require_login

  def index
    if current_user.bands.count == 0
      redirect_to new_band_path
    else
      redirect_to current_user.active_band
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def new
    @band = Band.find(params[:band_id])
    @song = Song.new
  end

  def create
    @band = Band.find(params[:band_id])
    @song = @band.songs.build(song_params)
    if @song.save
      respond_to do |format|
        format.html { redirect_to @band }
        format.json { render json: { name: @song.name } }
      end
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def destroy
    if @song.destroy
      redirect_to :back
    end
  end

  def update
    if @song.update(song_params)
      respond_to do |format|
        format.html { redirect_to @song }
        format.json { render json: { success: true } }
      end
    else
      render :edit
    end
  end

  def lyrics
  end

  def sort
    params[:song].each_with_index do |id, index|
      song = Song.find(id)
      song.update(position: index + 1)
    end
    render nothing: true
    # respond_to do |format|
    #   format.json { render json: {success: true}}
    # end
  end

  private

  def set_song
    @song = Song.find(params[:id])
    @band = @song.band
  end

  def song_params
    params.require(:song).permit(:name, :band_id, :lyrics)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-danger", notice: "alert-success" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type.to_sym)} fade in") do
        concat content_tag(:button, '', class: "glyphicon glyphicon-remove close")
        concat message
      end)
    end
    nil
  end

end

app/helpers/audio_clips_helper.rb
module AudioClipsHelper
end

app/helpers/audio_notes_helper.rb
module AudioNotesHelper
end

app/helpers/band_invites_helper.rb
module BandInvitesHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
  def lyric_format(string)
    string = string.split /\//
    string = string.map { |phrase| "<span class='phrase'>#{phrase}</span>" }.join
    simple_format(string)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.slim
/nav.navbar.navbar-default
/  .container
/    /! Brand and toggle get grouped for better mobile display
/    .navbar-headerstr
/      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
/        span.sr-only Toggle navigation
/        span.icon-bar
/        span.icon-bar
/        span.icon-bar
/      a.navbar-brand href="#"  Bandolier
/    /! Collect the nav links, forms, and other content for toggling
/    #bs-example-navbar-collapse-1.collapse.navbar-collapse
/      ul.nav.navbar-nav
/        li class=('active' if controller.controller_name == 'bands')
/          = link_to "Home", (current_user.active_band if current_user)
/      ul.nav.navbar-nav.navbar-right
/        li
/        - if current_user
/          - if current_user.active_band
/            li.dropdown
/              a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
/                = current_user.active_band.try(:name)
/                span.caret
/              ul.dropdown-menu
/                - current_user.bands.each do |band|
/                  li
/                    = link_to band.name, set_active_band_path(band_id: band), method: :post
/                li.divider role="separator"
/                li = link_to "Add Band", new_band_path
/          li.dropdown
/            a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
/              = current_user.email
/              span.caret
/            ul.dropdown-menu
/              li
/                a href="#"  Action
/              li
/                a href="#"  Another action
/              li
/                a href="#"  Something else here
/              li.divider role="separator"
/              li = link_to "Sign Out", sign_out_path, method: :delete
/        - else
/          li = link_to "Sign In", sign_in_path
    /! /.navbar-collapse
  /! /.container-fluid

nav.navi
  .container
    .navi-center
      .site-logo = link_to "BANDOLIER", root_url
    .navi-right
      - if current_user
        .site-link = link_to "Settings", settings_path
        .site-link = link_to "Sign Out", sign_out_path, method: :delete
      - else
        .site-link = link_to "Register", new_user_path
        .site-link = link_to "Sign In", sign_in_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bandolier</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>

  <div id="bg"></div>

  <div class="container">
    <div class="flash">
      <%= flash_messages %>
    </div>
    <%= yield %>
  </div>


</body>
</html>